### ISSUE TITLE
Migrated DB is an empty sql file

### ISSUE THREAD

**Issue by eraydiler** [bradt/wp-migrate-db#47]
Hi, i have been using this useful plugin for months, there was no issue until now. I am trying to migrate db of my blog for using in my local computer. But generated file is empty. The following is what does its content have. What kind of problem do i have ?

"# WordPress MySQL database migration"
"#"
"# Generated: Friday 16. January 2015 15:06 UTC"
"# Hostname: localhost"
"# Database: `db_name`"
"# --------------------------------------------------------"

/*!40101 SET NAMES utf8 */;

SET sql_mode='NO_AUTO_VALUE_ON_ZERO';

**Comment by bradt** [comment]
https://wordpress.org/support/topic/this-forum-is-checked-every-2-weeks?replies=1
