### ISSUE TITLE
new release is likely needed

### ISSUE THREAD

**Issue by highsteppin** [bradt/wp-migrate-db#50]
Hi - I don't want to draw too much attention to this issue, I think you may need to release a new version as soon as possible to address this concern: https://yoast.com/coordinated-security-release/

More specifically a few uses of add_query_arg in wpmdb-base.php

Also see: https://developer.wordpress.org/reference/functions/add_query_arg/

**Comment by bradt** [comment]
Nope, both instances where `add_query_arg()` is used are not vulnerable. We pass in a hard coded URL as the second argument, so the function doesn't use `$_SERVER['REQUEST_URI']` to construct the URL.

**Comment by highsteppin** [comment]
It's the lack of a third argument that is the problem - without it $_SERVER['REQUEST_URI'] is used. 

Or are you claiming this documentation is incorrect? -> https://developer.wordpress.org/reference/functions/add_query_arg/

**Comment by highsteppin** [comment]
I see, because you are passing in an array for the first parameter, the function won't use $_SERVER['REQUEST_URI'] in the absence of a third parameter. I was confused by this as I hadn't noticed in the source code that the type (array or string) of the first parameter will determine the number of parameters that must be passed in order to avoid the XSS vulnerability. 

I can see why many people are advocating to always escape the return of this function, as it would be easy to accidentally mess this up and leave the code vulnerable. For instance, in the future if you were to modify the type of the your first parameter so it was a string, then you could inadvertently create a vulnerability.

**Comment by bradt** [comment]
> I see, because you are passing in an array for the first parameter, the function won't use $_SERVER['REQUEST_URI'] in the absence of a third parameter.

Nope. It's because we're passing in a URL as the 2nd param.

**Comment by highsteppin** [comment]
Your code is secure against an XSS attack not only because you passed in a URL for the 2nd parameter, but also because the first parameter is an array. If the first parameter were a string and the third parameter absent, then add_query_arg() definitely would use $_SERVER['REQUEST_URI'] to formulate the return. In that scenario your hardcoded URL from the 2nd parameter would simply be included in the query string of the return. The logic in the first conditional statement in add_query_arg() will ensure this to be the case (lines 748-750  https://developer.wordpress.org/reference/functions/add_query_arg/)

Your code is safe from XSS, but I felt it was worth responding in case someone else is reading this thread, or if in the future you plan on using add_query_arg() with a string as the first parameter and no value for the third parameter.
